# Generated by Django 5.0.1 on 2024-01-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNPJ', models.CharField(max_length=14)),
                ('legalName', models.CharField(max_length=255)),
                ('businessName', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('profilePic', models.ImageField(upload_to='main/prof_pics/%Y/%m/%d/')),
                ('registrationStatus', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('validatingDocument', models.FileField(upload_to='')),
                ('isPartner', models.BooleanField(default=False)),
                ('isValid', models.BooleanField(default=False)),
            ],
        ),
    ]
