# Generated by Django 5.0.1 on 2024-01-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_socialmedia_company_socialmedia_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(choices=[('WhatsApp', 'Whatsapp'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('TikTok', 'TikTok'), ('Telegram', 'Telegram'), ('Kwai', 'Kwai'), ('Twitter', 'Twitter'), ('Pinterest', 'Pinterest'), ('LinkedIn', 'LinkedIn'), ('Snapchat', 'Snapchat')], default='Instagram', max_length=9),
        ),
    ]
