# Generated by Django 5.0.1 on 2024-01-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_buycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
