# Generated by Django 5.0.1 on 2024-01-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_socialmedia_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='picture',
            new_name='mainPicture',
        ),
        migrations.AddField(
            model_name='products',
            name='fourthPicture',
            field=models.ImageField(blank=True, null=True, upload_to='main/products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='products',
            name='secondPicture',
            field=models.ImageField(blank=True, null=True, upload_to='main/products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='products',
            name='thirdPicture',
            field=models.ImageField(blank=True, null=True, upload_to='main/products/%Y/%m/%d/'),
        ),
    ]
