# Generated by Django 5.0.1 on 2024-02-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_picture_products_mainpicture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.companies'),
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='details',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='mainPicture',
            field=models.ImageField(default='', upload_to='main/services/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='secondPicture',
            field=models.ImageField(blank=True, null=True, upload_to='main/services/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='thirdPicture',
            field=models.ImageField(blank=True, null=True, upload_to='main/services/%Y/%m/%d/'),
        ),
    ]
