# Generated by Django 5.0.1 on 2024-02-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_services_company_services_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='password',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
