# Generated by Django 5.0.1 on 2024-02-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_companies_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='rating',
        ),
        migrations.AlterField(
            model_name='companies',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
