# Generated by Django 5.0.1 on 2024-02-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_companies_rating_alter_companies_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='address',
            new_name='addressNumber',
        ),
        migrations.AddField(
            model_name='companies',
            name='city',
            field=models.CharField(default='Blumenau', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='complement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companies',
            name='country',
            field=models.CharField(default='Brasil', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='neigborhood',
            field=models.CharField(default='Badenfurt', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='state',
            field=models.CharField(default='SC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='streetAddress',
            field=models.CharField(default='Rua inventada', max_length=255),
            preserve_default=False,
        ),
    ]
