# Generated by Django 5.0.1 on 2024-02-09 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_address_companies_addressnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='country',
        ),
    ]
