# Generated by Django 5.0.1 on 2024-02-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_companies_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='CNPJ',
            field=models.CharField(max_length=50),
        ),
    ]
