# Generated by Django 5.0.1 on 2024-02-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEP', models.CharField(max_length=9)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('neigborhood', models.CharField(max_length=255)),
                ('streetAddress', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('complement', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.address'),
        ),
    ]
