# Generated by Django 5.0.1 on 2024-02-14 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_userprofile_aboutme_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='addressNumber',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='city',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='isValid',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='neigborhood',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='password',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='registrationStatus',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='state',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='streetAddress',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='validatingDocument',
        ),
        migrations.AddField(
            model_name='companies',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.address'),
        ),
        migrations.AddField(
            model_name='companies',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isPartner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='serviceTer',
            field=models.CharField(choices=[('Nenhum', 'Nenhum'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Nenhum', max_length=8),
        ),
    ]
