# Generated by Django 5.0.1 on 2024-02-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_companies_cep_remove_companies_addressnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isPartner',
        ),
    ]
