# Generated by Django 5.0.1 on 2024-02-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_remove_userprofile_ispartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.CharField(max_length=100),
        ),
    ]
