# Generated by Django 5.0.1 on 2024-02-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_buycart_customer_buycart_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycart',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
