# Generated by Django 5.0.1 on 2024-02-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='businessEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
