# Generated by Django 5.0.1 on 2024-02-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_employee_businessemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
