# Generated by Django 5.0.1 on 2024-02-21 11:52

import django.db.models.deletion
import utils.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='profilePic',
            field=models.ImageField(upload_to=utils.models_utils.company_image_upload),
        ),
        migrations.AlterField(
            model_name='products',
            name='fourthPicture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models_utils.product_image_upload),
        ),
        migrations.AlterField(
            model_name='products',
            name='mainPicture',
            field=models.ImageField(upload_to=utils.models_utils.product_image_upload),
        ),
        migrations.AlterField(
            model_name='products',
            name='secondPicture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models_utils.product_image_upload),
        ),
        migrations.AlterField(
            model_name='products',
            name='thirdPicture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models_utils.product_image_upload),
        ),
        migrations.AlterField(
            model_name='services',
            name='mainPicture',
            field=models.ImageField(upload_to=utils.models_utils.service_image_upload),
        ),
        migrations.AlterField(
            model_name='services',
            name='secondPicture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models_utils.service_image_upload),
        ),
        migrations.AlterField(
            model_name='services',
            name='thirdPicture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models_utils.service_image_upload),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.models_utils.profile_image_upload),
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=utils.models_utils.request_image_upload)),
                ('type', models.CharField(choices=[('Produto', 'Produto'), ('Serviço', 'Serviço')], default='Serviço', max_length=7)),
                ('maxBudget', models.DecimalField(decimal_places=2, max_digits=20)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.userprofile')),
            ],
        ),
    ]
